# CHAPTER 13 | 예외 처리와 C 언어와의 링크 지정 <BR>
>13.1 실행 오류와 오류 처리 <BR>

**실행 오류의 종류와 원인**<BR>- 개발자의 논리가 잘못된 경우<BR>- 예외에 대한 대책을 준비하지 않는 경우
```C++
// if 문과 리턴 값을 이용한 오류 처리
#include <iostream>
using namespace std;

int getExp(int base, int exp)
{
    if(base <= 0 || exp <= 0)
    {
        return -1;
    }
    
    int value = 1;
    for(int n = 0; n < exp; n++)
    {
       value = value * base; 
    }
    return value;
}

int main()
{
    int v = 0;
    v = getExp(2, 3);
    if(v != -1)
    {
        cout << "2의 3승은 " << v << "입니다." << endl;
    }
    else
    {
        cout << "오류. 2의 3승은 계산할 수 없습니다. " << endl;
    }

    int e = 0;
    e = getExp(2, -3);
    if(e != -1)
    {
        cout << "2의 3승은 " << e << "입니다." << endl;
    }
    else
    {
        cout << "오류. 2의 3승은 계산할 수 없습니다. " << endl;
    }
}
```
<BR>

> 13.2 예외와 예외 처리 <BR>

예외 : 실행 중 프로그램의 오동작이나 결과에 영향을 미치는 예상치 못한 상황 발생<BR>

**예외 기본 처리 방식, try-throw-catch**
```C++
try
{
    // 예외가 발생할 가능성이 있는 실행문
    // 예외를 발견한다면
    {
        throw xxx;
        // 예외 발생을 알림. xxx는 예외 값
    }
}

catch(/*처리할 예외 파라미터 선언*/)
{
    // 예외 처리문
}
```
- 예외가 발생할 소지가 있는 문장들을 try{ } 블록으로 묶고, 예외를 처리할 catch() { } 블록을 바로 연결하여 선언한다.<BR>
- 하나의 try{ } 블록에 여러 개의 catch() { } 블록을 연달아 선언할 수 있다.<BR>
- 예외가 탐지도디면 throw 문을 실행하여 예외 발생을 알린다.<BR>

**throw 문**<BR>- 현재 실행 중인 프로그램 내에 예외의 발생을 알린다. "예외를 던진다" 라고 함
```C++
// 예시
throw 3; // int 타입의 예외 값 3을 던짐
throw "empty stack"; // char* 타입의 문자열 예외를 던짐
```
<BR>- throw 문이 실행되면 예외 값 타입과 일치하는 catch() { } 문이 실행되므로, <BR>throw문 다음에 있는 나머지 try { } 블록은 실행되지 않는다.<BR>

**catch(예외 파라미터){ } 문**<BR>- 예외 파라미터는 한 개만 선언 가능<BR>

```C++
// 예시
try
{
    throw "음수 불가능";
}

catch(const char* s)
{
    cout << s; // 음수 불가능 출력
}
```
<BR>

> 13.3 예외 처리에 대한 자세한 설명 <BR>

**하나의 try{ } 블록에 다수의 catch() { } 연결**<BR>
```C++
try
{
    throw "음수 불가능";
    throw 3;
}

catch(const char* s)
{
    // 문자열 타입의 예외 처리. "음수 불가능"이 s에 전달
}

catch(int x)
{
    // int 타입 예외 처리. 3이 x에 전달됨
}
```
<BR>

**함수를 포함하는 try{ } 블록**
```C++
int multiply(int x, int y)
{
    if(x < 0 || y < 0)
    {
        throw "음수 불가능"
    }
    else
    {
        return x * y;
    }
}

int main()
{
    try
    {
        int n = multiply(2, -3);
        cout << "곱은 " << n << endl;
    }
    catch(const char* negative)
    {
        cout << "exception happened : " << negative;
    }
}

// 실행 결과
// exception happened : 음수 불가능
```
<BR>

**throw 사용 시 주의 사항**<BR>(1) throw 문은 항상 try{ } 블록 안에서 실행되어야 한다.(그렇지 않으면 abort() 함수 호출하여 프로그램 종료시킴)<BR>(2) 예외를 처리할 catch() { } 블록이 없으면 프로그램은 종료된다.<BR>(3) catch 블록 내에도 try, catch 블록을 선언 할 수 있다.<BR><BR>

> 13.4 예외 클래스 만들기 <BR>
```C++
#include <iostream>
#include <string>
using namespace std;

class MyException
{
    int lineNo;
    string func;
    string msg;
public:
    MyException(int n, string f, string m)
    {
        lineNo = n;
        func = f;
        msg = m;
    }
    
    void print()
    {
        cout << func << ":" << lineNo << ", " << msg << endl;
    }
};

class DivideByZeroException : public MyException
{
public:
    DivideByZeroException(int lineNo, string func, string msg)
        : MyException(lineNo, func, msg)
    {

    }
};

class InvalidInputException : public MyException
{
public:
    InvalidInputException(int lineNo, string func, string msg)
        : MyException(lineNo, func, msg)
    {

    }
};

int main()
{
    int x, y;
    try
    {
        cout << "나눗셈을 합니다. 두 개의 양의 정수를 입력하세요>>";
        cin >> x >> y;
        if(x < 0 || y < 0)
        {
            throw InvalidInputException(33,"main()", "음수 입력 예외 발생");
        }

        if(y == 0)
        {
            throw DivideByZeroException(35, "main()", "0으로 나누는 예외 발생");
        }
        cout << (double)x / (double)y;
    }

    catch(DivideByZeroException &e)
    {
        e.print();
    }

    catch(InvalidInputException &e)
    {
        e.print();
    }
}

// 실행 결과
// 나눗셈을 합니다. 두 개의 양의 정수를 입력하세요>> 2 5
// 0.4

// 나눗셈을 합니다. 두 개의 양의 정수를 입력하세요>> 200 -3
// main():33, 음수 입력 예외 발생

// 나눗셈을 합니다. 두 개의 양의 정수를 입력하세요>> 20 0
// main():35, 0으로 나누는 예외 발생
```
<BR>

> 13.5 C++ 코드와 C 코드의 링킹 <BR>

모든 컴파일러는 소스 코드를 컴파일하여 목적 코드(obj 파일)를 만들 때, 소스 코드에 있는 변수, 함수, 클래스의 이름을 변형하여 저장한다.<BR>-> 이름 규칙 : naming mangling<BR>

**C 컴파일러의 이름 규칙**<BR>- 함수 이름 앞에 밑줄표시문자('_')를 붙인다.<BR>- 매개 변수의 존재나 리턴 타입은 전혀 반영되지 않는다. -> 함수 오버로딩 불가<BR>

**C++ 컴파일러의 이름 규칙**<BR>- 함수의 매개 변수 개수와 타입, 리턴 타입 등을 반영한다. -> 함수 오버로딩 가능<BR>- main() 함수만은 항상 _main으로 이름을 붙인다.<BR>

**C++ 프로그램에서 C 함수 호출 시 링크 오류가 발생하는 경우**<BR>- 원인 : 서로 이름 규칙이 달라서<BR>

**정상적인 링킹, extern "C"**<BR>- C 언어의 이름 규칙으로 컴파일 하도록 지시하여 해결한다.
```C++
extern "C" int f(int x, int y);

extern "C"
{
    int f(int x, int y);
    void g();
    char s(int []);
}

extern "C"
{
    #include "mycfunction.h"
}
```
<BR>

- - -
>Open Challenge <BR>

**CPU 시뮬레이션과 예외 만들기**<BR><BR>

> 연습문제<BR>


**실습 문제**
- - -
(참고) Open Challenge ~ 연습문제까지의 실습 내용은 Visual Studio -> 13 예외 처리와 C 언어와의 링크 지정에 작성함